// Automatically generated by sdns_decode with `make public-resolvers.h', do not edit !

#ifdef UPSTREAM_P0
  //sdns://AgMAAAAAAAAADTc4LjQ3LjE2My4xNDGgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984YYWRmcmVlLnVzYWJsZXByaXZhY3kubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P1
  //sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20 : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "94.140.14.1"
  #define UPSTREAM_PORT 5443
  #define UPSTREAM_PUBKEY "d12b47f252dcf2c2bbf8991086eaf79ce4495d8b16c8a0c4322e52ca3f390873"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\7" "default" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P2
  //sdns://AgMAAAAAAAAADDk0LjE0MC4xNS4xNSCaOjT3J965vKUQA9nOnDn48n3ZxSQpAcK6saROY1oCGQ9kbnMuYWRndWFyZC5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P3
  //sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNTo1NDQzILgxXdexS27jIKRw3C7Wsao5jMnlhvhdRUXWuMm1AFq6ITIuZG5zY3J5cHQuZmFtaWx5Lm5zMS5hZGd1YXJkLmNvbQ : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "94.140.14.1"
  #define UPSTREAM_PORT 5443
  #define UPSTREAM_PUBKEY "b8315dd7b14b6ee320a470dc2ed6b1aa398cc9e586f85d4545d6b8c9b5005aba"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\6" "family" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P4
  //sdns://AgMAAAAAAAAADDk0LjE0MC4xNS4xNiCaOjT3J965vKUQA9nOnDn48n3ZxSQpAcK6saROY1oCGRZkbnMtZmFtaWx5LmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P5
  //sdns://AQMAAAAAAAAAGVsyYTEwOjUwYzA6OmJhZDE6ZmZdOjU0NDMguDFd17FLbuMgpHDcLtaxqjmMyeWG-F1FRda4ybUAWrohMi5kbnNjcnlwdC5mYW1pbHkubnMxLmFkZ3VhcmQuY29t : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "b8315dd7b14b6ee320a470dc2ed6b1aa398cc9e586f85d4545d6b8c9b5005aba"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\6" "family" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P6
  //sdns://AQMAAAAAAAAAGFsyYTEwOjUwYzA6OmFkMTpmZl06NTQ0MyDRK0fyUtzywrv4mRCG6vec5EldixbIoMQyLlLKPzkIcyIyLmRuc2NyeXB0LmRlZmF1bHQubnMxLmFkZ3VhcmQuY29t : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "d12b47f252dcf2c2bbf8991086eaf79ce4495d8b16c8a0c4322e52ca3f390873"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\7" "default" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P7
  //sdns://AQMAAAAAAAAAEjk0LjE0MC4xNC4xNDA6NTQ0MyC16ETWuDo-PhJo62gfvqcN48X6aNvWiBQdvy7AZrLa-iUyLmRuc2NyeXB0LnVuZmlsdGVyZWQubnMxLmFkZ3VhcmQuY29t : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "94.140.14.14"
  #define UPSTREAM_PORT 5443
  #define UPSTREAM_PUBKEY "b5e844d6b83a3e3e1268eb681fbea70de3c5fa68dbd688141dbf2ec066b2dafa"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\12" "unfiltered" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P8
  //sdns://AgcAAAAAAAAADTk0LjE0MC4xNC4xNDAgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkaZG5zLXVuZmlsdGVyZWQuYWRndWFyZC5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P9
  //sdns://AQMAAAAAAAAAFlsyYTEwOjUwYzA6OjE6ZmZdOjU0NDMgtehE1rg6Pj4SaOtoH76nDePF-mjb1ogUHb8uwGay2volMi5kbnNjcnlwdC51bmZpbHRlcmVkLm5zMS5hZGd1YXJkLmNvbQ : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "b5e844d6b83a3e3e1268eb681fbea70de3c5fa68dbd688141dbf2ec066b2dafa"
  #define UPSTREAM_SRVNAME "\1" "2" "\10" "dnscrypt" "\12" "unfiltered" "\3" "ns1" "\7" "adguard" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P10
  //sdns://AgMAAAAAAAAADTE5My4yOS42Mi4xOTagzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZG9oLmNoaS5haGFkbnMubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P11
  //sdns://AgMAAAAAAAAADTQ1LjY3LjIxOS4yMDigzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984RZG9oLmxhLmFoYWRucy5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P12
  //sdns://AgMAAAAAAAAACTUuMi43NS43NaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhFkb2gubmwuYWhhZG5zLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P13
  //sdns://AgMAAAAAAAAADDQ1LjEzMi43NS4xNqDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhFkb2gucGwuYWhhZG5zLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P14
  //sdns://AgAAAAAAAAAACTIyMy41LjUuNSCY49XlNq8pWM0vfxT3BO9KJ20l4zzWXy5l9eTycnwTMA5kbnMuYWxpZG5zLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P15
  //sdns://AQcAAAAAAAAAEDE4NS4yMDQuMi44Ojg0NDMgmfGTecriYs8VCfSDIUo6U6yQ5g98itBT7FWH3yYVB1MZMi5kbnNjcnlwdC1jZXJ0LmFsdGVybmFtZQ : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "185.204.2."
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "99f19379cae262cf1509f483214a3a53ac90e60f7c8ad053ec5587df26150753"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "altername" "\0"
#endif
#ifdef UPSTREAM_P16
  //sdns://AQcAAAAAAAAAG1syYTA0OjUyMDA6ZmZmNDo6MTNmZl06ODQ0MyCZ8ZN5yuJizxUJ9IMhSjpTrJDmD3yK0FPsVYffJhUHUxkyLmRuc2NyeXB0LWNlcnQuYWx0ZXJuYW1l : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "99f19379cae262cf1509f483214a3a53ac90e60f7c8ad053ec5587df26150753"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "altername" "\0"
#endif
#ifdef UPSTREAM_P17
  //sdns://AgMAAAAAAAAADDg5LjM4LjEzMS4zOAAYZG5zbmwtbm9hZHMuYWxla2JlcmcubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P18
  //sdns://AQcAAAAAAAAAETg5LjM4LjEzMS4zODo0MzQzIKWHS9r0FoKY--wcnJl1Ar5aOUb91xsufvPUjid3rNRaHzIuZG5zY3J5cHQtY2VydC5hbXMtZG5zY3J5cHQtbmw : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "89.38.131.3"
  #define UPSTREAM_PORT 4343
  #define UPSTREAM_PUBKEY "a5874bdaf4168298fbec1c9c997502be5a3946fdd71b2e7ef3d48e2777acd45a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\17" "ams-dnscrypt-nl" "\0"
#endif
#ifdef UPSTREAM_P19
  //sdns://AQcAAAAAAAAAGlsyYTBjOmI5YzA6Zjo0NTFkOjoxXTo0MzQzIKWHS9r0FoKY--wcnJl1Ar5aOUb91xsufvPUjid3rNRaHzIuZG5zY3J5cHQtY2VydC5hbXMtZG5zY3J5cHQtbmw : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "a5874bdaf4168298fbec1c9c997502be5a3946fdd71b2e7ef3d48e2777acd45a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\17" "ams-dnscrypt-nl" "\0"
#endif
#ifdef UPSTREAM_P20
  //sdns://AgcAAAAAAAAADDg5LjM4LjEzMS4zOKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhJkbnNubC5hbGVrYmVyZy5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P21
  //sdns://AgcAAAAAAAAAFVsyYTBjOmI5YzA6Zjo0NTFkOjoxXaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhJkbnNubC5hbGVrYmVyZy5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P22
  //sdns://AgUAAAAAAAAAAKC8hFRehaL-5iAWO74cDW6sa3toE6vGROtou_hQdtyuYyCY49XlNq8pWM0vfxT3BO9KJ20l4zzWXy5l9eTycnwTMBBkb2h0cmlhbC5hdHQubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P23
  //sdns://AgcAAAAAAAAADDE5My43MC44NS4xMaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhFkb2guYm9ydHptZXllci5mcgEv : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P24
  //sdns://AgcAAAAAAAAAGVsyMDAxOjQxZDA6MzAyOjIyMDA6OjE4MF2gzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984RZG9oLmJvcnR6bWV5ZXIuZnIBLw : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P25
  //sdns://AgMAAAAAAAAADjE2LjE3MC4xNTAuMjIxoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOEGRucy5icmFobWEud29ybGQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P26
  //sdns://AgMAAAAAAAAAJ1syYTA1OmQwMTY6YWY4OjQwMDA6NzcxMDo2ZmM6YmRlMzpmZTBlXaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhBkbnMuYnJhaG1hLndvcmxkCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P27
  //sdns://AgYAAAAAAAAADTE4NS4xOTQuOTQuNzEADGRucy5jaXJjbC5sdQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P28
  //sdns://AgYAAAAAAAAAElsyYTAwOjU5ODA6OTQ6OjcxXQAMZG5zLmNpcmNsLmx1Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P29
  //sdns://AQEAAAAAAAAADjIwOC42Ny4yMjAuMjIwILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ : 
  // DNSSec
  // ! LOGGING
  // ! FILTERING
  #define UPSTREAM_HOST "208.67.220.220"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "b7351140206f225d3e2bd822d7fd691ea1c33cc8d6668d0cbe04bfabca43fb79"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "opendns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P30
  //sdns://AgAAAAAAAAAADDE0Ni4xMTIuNDEuMiBoU4_HgY6B0kIqkGBjb6UoKkP2Dc4bumDC1_Orq2YAlw9kb2gub3BlbmRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P31
  //sdns://AQEAAAAAAAAADjIwOC42Ny4yMjAuMTIzILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ : 
  // DNSSec
  // ! LOGGING
  // ! FILTERING
  #define UPSTREAM_HOST "208.67.220.123"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "b7351140206f225d3e2bd822d7fd691ea1c33cc8d6668d0cbe04bfabca43fb79"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "opendns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P32
  //sdns://AQEAAAAAAAAAEVsyNjIwOjExOTozNTo6MzVdILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ : 
  // DNSSec
  // ! LOGGING
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "b7351140206f225d3e2bd822d7fd691ea1c33cc8d6668d0cbe04bfabca43fb79"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "opendns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P33
  //sdns://AQEAAAAAAAAAD1syNjIwOjA6Y2NjOjoyXSC3NRFAIG8iXT4r2CLX_WkeocM8yNZmjQy-BL-rykP7eRsyLmRuc2NyeXB0LWNlcnQub3BlbmRucy5jb20 : 
  // DNSSec
  // ! LOGGING
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "b7351140206f225d3e2bd822d7fd691ea1c33cc8d6668d0cbe04bfabca43fb79"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "opendns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P34
  //sdns://AgAAAAAAAAAAEFsyNjIwOjExOTpmYzo6Ml0gaFOPx4GOgdJCKpBgY2-lKCpD9g3OG7pgwtfzq6tmAJcPZG9oLm9wZW5kbnMuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P35
  //sdns://AQUAAAAAAAAADDE0Ni4xMTIuNDEuNCC3NRFAIG8iXT4r2CLX_WkeocM8yNZmjQy-BL-rykP7eRsyLmRuc2NyeXB0LWNlcnQub3BlbmRucy5jb20 : 
  // DNSSec
  // ! LOGGING
  // No-filtering
  #define UPSTREAM_HOST "146.112.41.4"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "b7351140206f225d3e2bd822d7fd691ea1c33cc8d6668d0cbe04bfabca43fb79"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "opendns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P36
  //sdns://AQMAAAAAAAAAEzE4NS4yMjguMTY4LjEwOjg0NDMgvKwy-tVDaRcfCDLWB1AnwyCM7vDo6Z-UGNx3YGXUjykRY2xlYW5icm93c2luZy5vcmc : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.228.168.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "bcac32fad54369171f0832d6075027c3208ceef0e8e99f9418dc776065d48f29"
  #define UPSTREAM_SRVNAME "\15" "cleanbrowsing" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P37
  //sdns://AQMAAAAAAAAAFDE4NS4yMjguMTY4LjE2ODo4NDQzILysMvrVQ2kXHwgy1gdQJ8MgjO7w6OmflBjcd2Bl1I8pEWNsZWFuYnJvd3Npbmcub3Jn : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.228.168.16"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "bcac32fad54369171f0832d6075027c3208ceef0e8e99f9418dc776065d48f29"
  #define UPSTREAM_SRVNAME "\15" "cleanbrowsing" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P38
  //sdns://AQMAAAAAAAAAEjE4NS4yMjguMTY4Ljk6ODQ0MyC8rDL61UNpFx8IMtYHUCfDIIzu8Ojpn5QY3HdgZdSPKRFjbGVhbmJyb3dzaW5nLm9yZw : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.228.168."
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "bcac32fad54369171f0832d6075027c3208ceef0e8e99f9418dc776065d48f29"
  #define UPSTREAM_SRVNAME "\15" "cleanbrowsing" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P39
  //sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P40
  //sdns://AgMAAAAAAAAABzEuMC4wLjMAGWZhbWlseS5jbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P41
  //sdns://AgMAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTExM10AGWZhbWlseS5jbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P42
  //sdns://AgMAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTAwM10AGWZhbWlseS5jbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P43
  //sdns://AgcAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTExMV0AIDFkb3QxZG90MWRvdDEuY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P44
  //sdns://AgcAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTAwMV0AIDFkb3QxZG90MWRvdDEuY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P45
  //sdns://AgMAAAAAAAAABzEuMC4wLjIAG3NlY3VyaXR5LmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P46
  //sdns://AgMAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTExMl0AG3NlY3VyaXR5LmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P47
  //sdns://AgMAAAAAAAAAFlsyNjA2OjQ3MDA6NDcwMDo6MTAwMl0AG3NlY3VyaXR5LmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P48
  //sdns://AQUAAAAAAAAACjguMjAuMjQ3LjIg0sJUqpYcHsoXmZb1X7yAHwg2xyN5q1J-zaiGG-Dgs7AoMi5kbnNjcnlwdC1jZXJ0LnNoaWVsZC0yLmRuc2J5Y29tb2RvLmNvbQ : 
  // DNSSec
  // ! LOGGING
  // No-filtering
  #define UPSTREAM_HOST "8.20.247.2"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "d2c254aa961c1eca179996f55fbc801f0836c72379ab527ecda8861be0e0b3b0"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "shield-2" "\13" "dnsbycomodo" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P49
  //sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P50
  //sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMg : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P51
  //sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMw : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P52
  //sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tBy9mYW1pbHk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P53
  //sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tCy91bmNlbnNvcmVk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P54
  //sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMA : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P55
  //sdns://AQIAAAAAAAAADTk0LjE5OC40MS4yMzUgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "94.198.41.235"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P56
  //sdns://AQIAAAAAAAAADjM3LjEyMC4xNDIuMTE1IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.142.115"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P57
  //sdns://AQIAAAAAAAAADTM3LjEyMC4yMzYuMTEgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.236.11"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P58
  //sdns://AQIAAAAAAAAADTM3LjEyMC4yMTcuNzUgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.217.75"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P59
  //sdns://AQIAAAAAAAAADjE3Ny41NC4xNDUuMTMxIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "177.54.145.131"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P60
  //sdns://AQIAAAAAAAAADjM3LjEyMC4xNTIuMjM1IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.152.235"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P61
  //sdns://AQIAAAAAAAAADzIxNy4xMzguMjIwLjI0MyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "217.138.220.243"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P62
  //sdns://AQIAAAAAAAAADDE5OC43LjU4LjIyNyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "198.7.58.227"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P63
  //sdns://AQIAAAAAAAAACzE0Ni43MC44Mi4zIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "146.70.82.3"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P64
  //sdns://AQIAAAAAAAAADTM3LjEyMC4yMzIuNDMgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.232.43"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P65
  //sdns://AQIAAAAAAAAADjIxMy4yMDIuMjE2LjEyIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "213.202.216.12"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P66
  //sdns://AQIAAAAAAAAADzIxMy4yMDIuMjE2LjIzNiAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "213.202.216.236"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P67
  //sdns://AQIAAAAAAAAADjg1LjExNC4xMzguMTE5IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "85.114.138.119"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P68
  //sdns://AQIAAAAAAAAADjE4NS4xMTcuMTE4LjIwIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.117.118.20"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P69
  //sdns://AQIAAAAAAAAADTE2My4xNzIuMzQuNTYgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "163.172.34.56"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P70
  //sdns://AQIAAAAAAAAADTg2LjEwNi43NC4yMTkgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "86.106.74.219"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P71
  //sdns://AQIAAAAAAAAADjE3My4yMzQuNTYuMTE1IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "173.234.56.115"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P72
  //sdns://AQIAAAAAAAAADjE3Mi4xMDcuMTk5LjE5IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "172.107.199.19"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P73
  //sdns://AQIAAAAAAAAADzE2NS4yMzEuMjUzLjE2MyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "165.231.253.163"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P74
  //sdns://AQIAAAAAAAAADjM3LjEyMC4yMzUuMTg3IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.235.187"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P75
  //sdns://AQIAAAAAAAAADTgyLjIyMS4xMjguNDQgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "82.221.128.44"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P76
  //sdns://AQIAAAAAAAAADTc4LjEyOS4xNDAuNjUgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "78.129.140.65"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P77
  //sdns://AQIAAAAAAAAADzEwOS4yNDguMTQ5LjEzMyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "109.248.149.133"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P78
  //sdns://AQIAAAAAAAAADjE4NS4xODMuMTA2LjgzIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.183.106.83"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P79
  //sdns://AQIAAAAAAAAADTE5NS4xMi40OC4xNzEgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "195.12.48.171"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P80
  //sdns://AQIAAAAAAAAADjE3OC4xNzUuMTI5LjE2IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "178.175.129.16"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P81
  //sdns://AQIAAAAAAAAADTEwMy4xNC4yNi4xOTAgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "103.14.26.190"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P82
  //sdns://AQIAAAAAAAAADzIxNy4xMzguMjE5LjIxOSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "217.138.219.219"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P83
  //sdns://AQIAAAAAAAAADzE0NC4xNjguMTY1LjE2MyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "144.168.165.163"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P84
  //sdns://AQIAAAAAAAAADjE1NS4yNTQuMjEuMjUwIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "155.254.21.250"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P85
  //sdns://AQIAAAAAAAAADTE4NS4xMDcuODAuODQgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "185.107.80.84"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P86
  //sdns://AQIAAAAAAAAADzE3Mi4xMDcuMjI2LjEwNyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "172.107.226.107"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P87
  //sdns://AQIAAAAAAAAADjkxLjIxOS4yMTUuMjI3IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "91.219.215.227"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P88
  //sdns://AQIAAAAAAAAADDM3LjEyMC4xNDcuMiAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.147.2"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P89
  //sdns://AQIAAAAAAAAADDIzLjE5LjI0NS44OCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "23.19.245.88"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P90
  //sdns://AQIAAAAAAAAADDIzLjE5LjI0NS44NCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "23.19.245.84"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P91
  //sdns://AQIAAAAAAAAADTEwNC4yNTUuMTc1LjIgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "104.255.175.2"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P92
  //sdns://AQIAAAAAAAAADTM3LjEyMC4yMTEuOTEgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.211.91"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P93
  //sdns://AQIAAAAAAAAADjkxLjIwNS4yMzAuMjI0IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "91.205.230.224"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P94
  //sdns://AQIAAAAAAAAADTE0Ni43MC42Ni4yMjcgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "146.70.66.227"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P95
  //sdns://AQIAAAAAAAAADjM3LjEyMC4yMDcuMTMxIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.207.131"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P96
  //sdns://AQIAAAAAAAAADDY0LjEyMC41LjI1MSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "64.120.5.251"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P97
  //sdns://AQIAAAAAAAAADjM3LjEyMC4xOTMuMjE5IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.193.219"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P98
  //sdns://AQIAAAAAAAAADzE3Mi4xMDcuMTU0LjIxMSAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "172.107.154.211"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P99
  //sdns://AQIAAAAAAAAADjE5My4zNy4yNTUuMjI3IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "193.37.255.227"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P100
  //sdns://AQIAAAAAAAAADzEyOC4xMjcuMTA0LjEwOCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "128.127.104.108"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P101
  //sdns://AQIAAAAAAAAADjM3LjEyMC4yMzQuMjUxIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "37.120.234.251"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P102
  //sdns://AQIAAAAAAAAADDE0Ni43MC4zMS40MyAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "146.70.31.43"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P103
  //sdns://AQIAAAAAAAAADTIwOS41OC4xNDcuMzYgMTNyrVlWMsJBa4cvCY-FG925ZShMbL6aTxkJZDDbqVoeMi5kbnNjcnlwdC1jZXJ0LmNyeXB0b3N0b3JtLmlz : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "209.58.147.36"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P104
  //sdns://AQIAAAAAAAAACzQ1LjM1LjM1Ljk5IDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "45.35.35.99"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P105
  //sdns://AQIAAAAAAAAACzQ1LjM1LjcyLjQzIDEzcq1ZVjLCQWuHLwmPhRvduWUoTGy-mk8ZCWQw26laHjIuZG5zY3J5cHQtY2VydC5jcnlwdG9zdG9ybS5pcw : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "45.35.72.43"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P106
  //sdns://AQIAAAAAAAAADDcxLjE5LjI1MS4zNCAxM3KtWVYywkFrhy8Jj4Ub3bllKExsvppPGQlkMNupWh4yLmRuc2NyeXB0LWNlcnQuY3J5cHRvc3Rvcm0uaXM : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "71.19.251.34"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "313372ad595632c2416b872f098f851bddb965284c6cbe9a4f19096430dba95a"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\13" "cryptostorm" "\2" "is" "\0"
#endif
#ifdef UPSTREAM_P107
  //sdns://AQcAAAAAAAAADDgzLjEzOC41NS4zNiBWtFK5EGeqJCoA9qB6APgcgCUN9FZvR8T22eqqP615MBcyLmRuc2NyeXB0LWNlcnQuZGN0LWF0MQ : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "83.138.55.36"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "56b452b91067aa242a00f6a07a00f81c80250df4566f47c4f6d9eaaa3fad7930"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "dct-at1" "\0"
#endif
#ifdef UPSTREAM_P108
  //sdns://AQcAAAAAAAAAEzIzLjEzNy4yNDkuMTE2Ojg0NDMgEWD0g0vsKFqwslGBKql8eTiu1RvK2dzZIxLfR7ctlAwXMi5kbnNjcnlwdC1jZXJ0LmRjdC1ubDE : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "23.137.249.11"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "1160f4834bec285ab0b251812aa97c7938aed51bcad9dcd92312df47b72d940c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "dct-nl1" "\0"
#endif
#ifdef UPSTREAM_P109
  //sdns://AQcAAAAAAAAADTE4NS4yMi4xNTQuMTkgaWn7WaFj7FQw_9F1qge8LMND5xUdAtagWFZPPYRok1kXMi5kbnNjcnlwdC1jZXJ0LmRjdC1ydTE : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "185.22.154.19"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "6969fb59a163ec5430ffd175aa07bc2cc343e7151d02d6a058564f3d84689359"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "dct-ru1" "\0"
#endif
#ifdef UPSTREAM_P110
  //sdns://AQMAAAAAAAAAEjc4LjQ3LjIxMi4yMTE6OTQ0MyBNRN4TaVynkcwkVAbSBrCvr4X3c3Cygz_4VDUcRhhhYx4yLmRuc2NyeXB0LWNlcnQuRGVDbG91ZFVzLXRlc3Q : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "78.47.212.21"
  #define UPSTREAM_PORT 9443
  #define UPSTREAM_PUBKEY "4d44de13695ca791cc245406d206b0afaf85f77370b2833ff854351c46186163"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\16" "DeCloudUs-test" "\0"
#endif
#ifdef UPSTREAM_P111
  //sdns://AQMAAAAAAAAAHFsyYTAxOjRmODoxM2E6MjUwYjo6MzBdOjk0NDMgTUTeE2lcp5HMJFQG0gawr6-F93NwsoM_-FQ1HEYYYWMeMi5kbnNjcnlwdC1jZXJ0LkRlQ2xvdWRVcy10ZXN0 : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "4d44de13695ca791cc245406d206b0afaf85f77370b2833ff854351c46186163"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\16" "DeCloudUs-test" "\0"
#endif
#ifdef UPSTREAM_P112
  //sdns://AQcAAAAAAAAADTUyLjY1LjIzNS4xMjkg5Q00RDDBkwx3fUaa0_etjz4iH3lLBOqsg95bYDmV07MdMi5kbnNjcnlwdC1jZXJ0LmRlZmZlci1kbnMuYXU : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "52.65.235.129"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "e50d344430c1930c777d469ad3f7ad8f3e221f794b04eaac83de5b603995d3b3"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\12" "deffer-dns" "\2" "au" "\0"
#endif
#ifdef UPSTREAM_P113
  //sdns://AQMAAAAAAAAAEjE2Mi4xOS4xMjkuMjA6NTQ0MyBLAxD2I-nLlzrjDQhX_eNLqCb-_DIIEiH7MBG2gbliLRsyLmRuc2NyeXB0LWNlcnQuYjMzLm5ldHdvcms : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "162.19.129.2"
  #define UPSTREAM_PORT 5443
  #define UPSTREAM_PUBKEY "4b0310f623e9cb973ae30d0857fde34ba826fefc32081221fb3011b681b9622d"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\3" "b33" "\7" "network" "\0"
#endif
#ifdef UPSTREAM_P114
  //sdns://AgcAAAAAAAAADTE4NS45NS4yMTguNDKgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984cZG5zLmRpZ2l0YWxlLWdlc2VsbHNjaGFmdC5jaAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P115
  //sdns://AgcAAAAAAAAADTE4NS45NS4yMTguNDOgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984cZG5zLmRpZ2l0YWxlLWdlc2VsbHNjaGFmdC5jaAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P116
  //sdns://AgcAAAAAAAAAD1syYTA1OmZjODQ6OjQyXaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhxkbnMuZGlnaXRhbGUtZ2VzZWxsc2NoYWZ0LmNoCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P117
  //sdns://AgcAAAAAAAAAD1syYTA1OmZjODQ6OjQzXaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhxkbnMuZGlnaXRhbGUtZ2VzZWxsc2NoYWZ0LmNoCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P118
  //sdns://AgcAAAAAAAAADjk0LjEzMC4xMzUuMjAzoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOE2Rucy5kaWdpdGFsc2l6ZS5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P119
  //sdns://AgcAAAAAAAAAGVsyYTAxOjRmODoxM2I6MzQwNzo6ZmFjZV2gzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984TZG5zLmRpZ2l0YWxzaXplLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P120
  //sdns://AgcAAAAAAAAADjY4LjE4My4yNTMuMjAwoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOFGRuczEucnlhbi1wYWxtZXIuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P121
  //sdns://AgMAAAAAAAAADzE3Mi4xMDQuMjA2LjE3NKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhRkbnMudGhlcmlmbGVtYW4ubmFtZQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P122
  //sdns://AQcAAAAAAAAADDg0LjIwMC43MC40MCBATVoA32LgIUTsC0hxmLlKGa_o5PRngHyldrEei5T5sCMyLmRuc2NyeXB0LWNlcnQucmVzb2x2ZXIyLmRucy53YXRjaA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "84.200.70.40"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "404d5a00df62e02144ec0b487198b94a19afe8e4f467807ca576b11e8b94f9b0"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "resolver2" "\3" "dns" "\5" "watch" "\0"
#endif
#ifdef UPSTREAM_P123
  //sdns://AQcAAAAAAAAAHFsyMDAxOjE2MDg6MTA6MjU6OjkyNDk6ZDY5Yl0gQE1aAN9i4CFE7AtIcZi5Shmv6OT0Z4B8pXaxHouU-bAjMi5kbnNjcnlwdC1jZXJ0LnJlc29sdmVyMi5kbnMud2F0Y2g : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "404d5a00df62e02144ec0b487198b94a19afe8e4f467807ca576b11e8b94f9b0"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "resolver2" "\3" "dns" "\5" "watch" "\0"
#endif
#ifdef UPSTREAM_P124
  //sdns://AQMAAAAAAAAAETQ1LjkxLjkyLjEyMTo4NDQzIIUTqWvE4INLlQ1jtQLo0-LVTQSWayYCkzTpBx26I_wrGzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "45.91.92.12"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "8513a96bc4e0834b950d63b502e8d3e2d54d04966b26029334e9071dba23fc2b"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "blahdns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P125
  //sdns://AQMAAAAAAAAAEjc4LjQ2LjI0NC4xNDM6ODQ0MyCFE6lrxOCDS5UNY7UC6NPi1U0ElmsmApM06QcduiP8KxsyLmRuc2NyeXB0LWNlcnQuYmxhaGRucy5jb20 : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "78.46.244.14"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "8513a96bc4e0834b950d63b502e8d3e2d54d04966b26029334e9071dba23fc2b"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "blahdns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P126
  //sdns://AQMAAAAAAAAAG1syYTAxOjRmODpjMTc6ZWM2Nzo6MV06ODQ0MyCFE6lrxOCDS5UNY7UC6NPi1U0ElmsmApM06QcduiP8KxsyLmRuc2NyeXB0LWNlcnQuYmxhaGRucy5jb20 : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "8513a96bc4e0834b950d63b502e8d3e2d54d04966b26029334e9071dba23fc2b"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "blahdns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P127
  //sdns://AQcAAAAAAAAADzE5My4xOTEuMTg3LjEwNyAzWmXOT_I8k2BKJzxIJ_iYoXRQRWcR0Q1FFyrJWtvogxsyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuYmU : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "193.191.187.107"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "335a65ce4ff23c93604a273c4827f898a17450456711d10d45172ac95adbe883"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\2" "be" "\0"
#endif
#ifdef UPSTREAM_P128
  //sdns://AQcAAAAAAAAADzE2Ny4xMTQuMjIwLjEyNSAaU6PJUHicvdELGTOkaJtshGpA8bc9F1KuysmCnst84h0yLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQuY2EtMQ : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "167.114.220.125"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "1a53a3c950789cbdd10b1933a4689b6c846a40f1b73d1752aecac9829ecb7ce2"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\4" "ca-1" "\0"
#endif
#ifdef UPSTREAM_P129
  //sdns://AgcAAAAAAAAAEzE2Ny4xMTQuMjIwLjEyNTo0NTOgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984UZG5zMS5kbnNjcnlwdC5jYTo0NTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P130
  //sdns://AgcAAAAAAAAAKVsyNjA3OjUzMDA6NjE6OTVmOjcyODM6MTFkOTpmODY6ZTY4OV06NDUzoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOGWRuczEuaXB2Ni5kbnNjcnlwdC5jYTo0NTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P131
  //sdns://AQcAAAAAAAAAJVsyNjA3OjUzMDA6NjE6OTVmOjcyODM6MTFkOTpmODY6ZTY4OV0gINkZ1Ow8UAjNxwpR6itPy_6KmTxkMdDsaB1epzhFq4AiMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTEtaXB2Ng : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "20d919d4ec3c5008cdc70a51ea2b4fcbfe8a993c6431d0ec681d5ea73845ab80"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\11" "ca-1-ipv6" "\0"
#endif
#ifdef UPSTREAM_P132
  //sdns://AQcAAAAAAAAADTE0OS41Ni4yMjguNDUgAQhUqztWp-7505FY_vaCC_-TojV8iRYI254V07vgEYUdMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTI : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "149.56.228.45"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "010854ab3b56a7eef9d39158fef6820bff93a2357c891608db9e15d3bbe01185"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\4" "ca-2" "\0"
#endif
#ifdef UPSTREAM_P133
  //sdns://AgcAAAAAAAAAETE0OS41Ni4yMjguNDU6NDUzoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOFGRuczIuZG5zY3J5cHQuY2E6NDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P134
  //sdns://AgcAAAAAAAAAKVsyNjA3OjUzMDA6NjE6OTVmOjcyODM6MTFkOTpmODY6ZTY5MF06NDUzoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOGWRuczIuaXB2Ni5kbnNjcnlwdC5jYTo0NTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P135
  //sdns://AQcAAAAAAAAAJVsyNjA3OjUzMDA6NjE6OTVmOjcyODM6MTFkOTpmODY6ZTY5MF0gmHxwqJfb2hUaNK1LVeqADvVhzASq1cV90sPYYfwX9CkiMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTItaXB2Ng : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "987c70a897dbda151a34ad4b55ea800ef561cc04aad5c57dd2c3d861fc17f429"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\11" "ca-2-ipv6" "\0"
#endif
#ifdef UPSTREAM_P136
  //sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDUzIH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5wbA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "178.216.201.12"
  #define UPSTREAM_PORT 2053
  #define UPSTREAM_PUBKEY "7f617cb81ea553d234c49bc279c74f7b5498050d1dbf111afee69963c647a169"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\2" "pl" "\0"
#endif
#ifdef UPSTREAM_P137
  //sdns://AQMAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDU0IH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5wbA : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "178.216.201.12"
  #define UPSTREAM_PORT 2054
  #define UPSTREAM_PUBKEY "7f617cb81ea553d234c49bc279c74f7b5498050d1dbf111afee69963c647a169"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\2" "pl" "\0"
#endif
#ifdef UPSTREAM_P138
  //sdns://AgcAAAAAAAAADzE2NS4yMjcuMjMzLjIwMAATZG9oLmRuc2NyeXB0LnVrOjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P139
  //sdns://AgcAAAAAAAAAGlsyYTAzOmIwYzA6MTpkMDo6ZWJlOmQwMDFdABNkb2guZG5zY3J5cHQudWs6NDQzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P140
  //sdns://AQcAAAAAAAAADTE2NS4yMzIuMzIuOTUgAdMO6A4gTdoYcdOhDyhRVGdlvxS02kQEpP8EbX2paDwbMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LnVr : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "165.232.32.95"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "01d30ee80e204dda1871d3a10f2851546765bf14b4da4404a4ff046d7da9683c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\2" "uk" "\0"
#endif
#ifdef UPSTREAM_P141
  //sdns://AQcAAAAAAAAAGlsyYTAzOmIwYzA6MTplMDo6NDg3OjEwMDFdIAHTDugOIE3aGHHToQ8oUVRnZb8UtNpEBKT_BG19qWg8GzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC51aw : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "01d30ee80e204dda1871d3a10f2851546765bf14b4da4404a4ff046d7da9683c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "dnscrypt" "\2" "uk" "\0"
#endif
#ifdef UPSTREAM_P142
  //sdns://AQMAAAAAAAAADDc4LjQ3LjY0LjE2MSATJeLOABXNSYcSJIoqR5_iUYz87Y4OecMLB84aEAKPrRBkbnNmb3JmYW1pbHkuY29t : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "78.47.64.161"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "1325e2ce0015cd498712248a2a479fe2518cfced8e0e79c30b07ce1a10028fad"
  #define UPSTREAM_SRVNAME "\14" "dnsforfamily" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P143
  //sdns://AgMAAAAAAAAADzE2Ny4yMzUuMjM2LjEwN6DMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhhkbnMtZG9oLmRuc2ZvcmZhbWlseS5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P144
  //sdns://AgMAAAAAAAAADzE2Ny4yMzUuMjM2LjEwN6DMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zidkbnMtZG9oLW5vLXNhZmUtc2VhcmNoLmRuc2ZvcmZhbWlseS5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P145
  //sdns://AQMAAAAAAAAADzEzNS4xODEuMTkzLjIyMiDrxcZ_hFtGE6tfATvQZYjxgl5pTY_e2cRH_ms8bEWofBBkbnNmb3JmYW1pbHkuY29t : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "135.181.193.222"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "ebc5c67f845b4613ab5f013bd06588f1825e694d8fded9c447fe6b3c6c45a87c"
  #define UPSTREAM_SRVNAME "\14" "dnsforfamily" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P146
  //sdns://AQMAAAAAAAAAF1syYTAxOjRmODoxYzE3OjRkZjg6OjFdIBMl4s4AFc1JhxIkiipHn-JRjPztjg55wwsHzhoQAo-tEGRuc2ZvcmZhbWlseS5jb20 : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "1325e2ce0015cd498712248a2a479fe2518cfced8e0e79c30b07ce1a10028fad"
  #define UPSTREAM_SRVNAME "\14" "dnsforfamily" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P147
  //sdns://AgMAAAAAAAAADDE3Ni45LjkzLjE5OKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zgtkbnNmb3JnZS5kZQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P148
  //sdns://AgAAAAAAAAAAAKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zglkbnNsb3cubWUKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P149
  //sdns://AgMAAAAAAAAAAKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhFkbnMuZG5zd2FyZGVuLmNvbQwvYWR1bHRmaWx0ZXI : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P150
  //sdns://AQcAAAAAAAAADDEzNy42Ni42LjE0NiDg_LCuCApY3CtucAKfyQyqk3g9NAq607r906qVDWVBLiwyLmRuc2NyeXB0LWNlcnQuZG5zd2FyZGVuLXVuY2Vuc29yZWQtYW55Y2FzdA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "137.66.6.146"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "e0fcb0ae080a58dc2b6e70029fc90caa93783d340abad3bafdd3aa950d65412e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\34" "dnswarden-uncensored-anycast" "\0"
#endif
#ifdef UPSTREAM_P151
  //sdns://AQcAAAAAAAAAFDE4OC4yNDQuMTE3LjExNDoxNDQzIOK0J6XON4YjPmXjlonI5Lx0ZenB5Din7hrX-8uYlDxHKjIuZG5zY3J5cHQtY2VydC5kbnN3YXJkZW4tdW5jZW5zb3JlZC1zd2lzcw : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "188.244.117.11"
  #define UPSTREAM_PORT 1443
  #define UPSTREAM_PUBKEY "e2b427a5ce3786233e65e39689c8e4bc7465e9c1e438a7ee1ad7fbcb98943c47"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\32" "dnswarden-uncensored-swiss" "\0"
#endif
#ifdef UPSTREAM_P152
  //sdns://AgMAAAAAAAAAAAAVZG9oLmNsZWFuYnJvd3Npbmcub3JnEi9kb2gvYWR1bHQtZmlsdGVyLw : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P153
  //sdns://AgMAAAAAAAAAAAAVZG9oLmNsZWFuYnJvd3Npbmcub3JnEy9kb2gvZmFtaWx5LWZpbHRlci8 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P154
  //sdns://AgMAAAAAAAAAAAAVZG9oLmNsZWFuYnJvd3Npbmcub3JnFS9kb2gvc2VjdXJpdHktZmlsdGVyLw : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P155
  //sdns://AgcAAAAAAAAACzEwNC4yMS42Ljc4AA1kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P156
  //sdns://AgcAAAAAAAAADjE3Mi42Ny4xMzQuMTU3AA1kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P157
  //sdns://AgcAAAAAAAAAGlsyNjA2OjQ3MDA6MzAzNzo6NjgxNTo2NGVdABJkb2gtaXB2Ni5jcnlwdG8uc3gKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P158
  //sdns://AgcAAAAAAAAAG1syNjA2OjQ3MDA6MzAzNjo6YWM0Mzo4NjlkXQASZG9oLWlwdjYuY3J5cHRvLnN4Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P159
  //sdns://AgcAAAAAAAAAAKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhRpYmtzdHVybS5zeW5vbG9neS5tZQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P160
  //sdns://AgMAAAAAAAAADDIxMi41Mi4wLjEyMiC00mapDYeq93KU38D1wQdQ8CGA8TJtF_1fknJi-UdrxBJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P161
  //sdns://AgcAAAAAAAAAAKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhZkb2guYXBwbGllZHByaXZhY3kubmV0Bi9xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P162
  //sdns://AgcAAAAAAAAACjUuMS42Ni4yNTWgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984NZG9oLmZmbXVjLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P163
  //sdns://AgcAAAAAAAAADjE4NS4xNTAuOTkuMjU1oMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffODWRvaC5mZm11Yy5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P164
  //sdns://AgcAAAAAAAAAFVsyMDAxOjY3ODplNjg6ZjAwMDo6XaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zg1kb2guZmZtdWMubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P165
  //sdns://AgcAAAAAAAAAFVsyMDAxOjY3ODplZDA6ZjAwMDo6XaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zg1kb2guZmZtdWMubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P166
  //sdns://AgMAAAAAAAAADDEwNC4yMS42NS42MAAOZG9oLnRpYXJhcC5vcmcKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P167
  //sdns://AgMAAAAAAAAAG1syNjA2OjQ3MDA6MzAzNDo6NjgxNTo0MTNjXQAOZG9oLnRpYXJhcC5vcmcKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P168
  //sdns://AgcAAAAAAAAAE1syMDAxOjY3YzoyMWVjOjo1M10gXMJdnIoy7PLLu5Hr9wvZVsUgOfnyDoQJ2mFUcVI21x0SZG5zY2FjaGUuZS11dHAubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P169
  //sdns://AQYAAAAAAAAAEzE4NS4xMzQuMTk2LjU0Ojg0NDMgfsvvPi8BgDKNYODh0ewj5Oh32OoJoZNwGgTWs8C-i-EfMi5kbnNjcnlwdC1jZXJ0LnJkbnMuZmFlbGl4Lm5ldA : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "185.134.196.5"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "7ecbef3e2f0180328d60e0e1d1ec23e4e877d8ea09a193701a04d6b3c0be8be1"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "rdns" "\6" "faelix" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P170
  //sdns://AQYAAAAAAAAAEzE4NS4xMzQuMTk2LjU1Ojg0NDMgfsvvPi8BgDKNYODh0ewj5Oh32OoJoZNwGgTWs8C-i-EfMi5kbnNjcnlwdC1jZXJ0LnJkbnMuZmFlbGl4Lm5ldA : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "185.134.196.5"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "7ecbef3e2f0180328d60e0e1d1ec23e4e877d8ea09a193701a04d6b3c0be8be1"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "rdns" "\6" "faelix" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P171
  //sdns://AQYAAAAAAAAAEjQ2LjIyNy4yMDAuNTQ6ODQ0MyB-y-8-LwGAMo1g4OHR7CPk6HfY6gmhk3AaBNazwL6L4R8yLmRuc2NyeXB0LWNlcnQucmRucy5mYWVsaXgubmV0 : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "46.227.200.5"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "7ecbef3e2f0180328d60e0e1d1ec23e4e877d8ea09a193701a04d6b3c0be8be1"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "rdns" "\6" "faelix" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P172
  //sdns://AQYAAAAAAAAAFFsyYTAxOjllMDA6OjU0XTo4NDQzIH7L7z4vAYAyjWDg4dHsI-Tod9jqCaGTcBoE1rPAvovhHzIuZG5zY3J5cHQtY2VydC5yZG5zLmZhZWxpeC5uZXQ : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "7ecbef3e2f0180328d60e0e1d1ec23e4e877d8ea09a193701a04d6b3c0be8be1"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "rdns" "\6" "faelix" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P173
  //sdns://AQYAAAAAAAAAFFsyYTAxOjllMDA6OjU1XTo4NDQzIH7L7z4vAYAyjWDg4dHsI-Tod9jqCaGTcBoE1rPAvovhHzIuZG5zY3J5cHQtY2VydC5yZG5zLmZhZWxpeC5uZXQ : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "7ecbef3e2f0180328d60e0e1d1ec23e4e877d8ea09a193701a04d6b3c0be8be1"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "rdns" "\6" "faelix" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P174
  //sdns://AQcAAAAAAAAADzUuMS42Ni4yNTU6ODQ0MyAH0Hrxz9xdmXadPwJmkKcESWXCdCdseRyu9a7zuQxG-hkyLmRuc2NyeXB0LWNlcnQuZmZtdWMubmV0 : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "5.1.66.255"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "07d07af1cfdc5d99769d3f026690a7044965c274276c791caef5aef3b90c46fa"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "ffmuc" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P175
  //sdns://AQcAAAAAAAAAGlsyMDAxOjY3ODplNjg6ZjAwMDo6XTo4NDQzIAfQevHP3F2Zdp0_AmaQpwRJZcJ0J2x5HK71rvO5DEb6GTIuZG5zY3J5cHQtY2VydC5mZm11Yy5uZXQ : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "07d07af1cfdc5d99769d3f026690a7044965c274276c791caef5aef3b90c46fa"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "ffmuc" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P176
  //sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbmgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUgalBisNF41VbxY7E7Gw8ZQ10CWIKRzHVYnf7m6xHI1cMKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P177
  //sdns://AgUAAAAAAAAAFlsyMDAxOjQ4NjA6NDg2MDo6ODg4OF2gHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbmgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUgalBisNF41VbxY7E7Gw8ZQ10CWIKRzHVYnf7m6xHI1cMKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P178
  //sdns://AgUAAAAAAAAACzc0LjgyLjQyLjQyoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffODG9yZG5zLmhlLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P179
  //sdns://AQcAAAAAAAAAEzIxMy4xOTYuMTkxLjk2Ojg0NDMgHK0AUhqiLSuBFR07jpBhKvko_oyqyWnot8z4cce7cKkYMi5kbnNjcnlwdC1jZXJ0Lmlia3N0dXJt : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "213.196.191.9"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "1cad00521aa22d2b81151d3b8e90612af928fe8caac969e8b7ccf871c7bb70a9"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "ibksturm" "\0"
#endif
#ifdef UPSTREAM_P180
  //sdns://AQMAAAAAAAAADjE3NC4xMzguMjEuMTI4IO-WgGbo2ZTwZdg-3dMa7u31bYZXRj5KykfN1_6Xw9T2HDIuZG5zY3J5cHQtY2VydC5kbnMudGlhci5hcHA : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "174.138.21.128"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "ef968066e8d994f065d83eddd31aeeedf56d8657463e4aca47cdd7fe97c3d4f6"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\3" "dns" "\4" "tiar" "\3" "app" "\0"
#endif
#ifdef UPSTREAM_P181
  //sdns://AgMAAAAAAAAADjE3NC4xMzguMjkuMTc1oMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffODGRvaC50aWFyLmFwcAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P182
  //sdns://AgMAAAAAAAAAG1syNDAwOjYxODA6MDpkMDo6NWY3Mzo0MDAxXaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zgxkb2gudGlhci5hcHAKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P183
  //sdns://AQMAAAAAAAAAG1syNDAwOjYxODA6MDpkMDo6NWY2ZTo0MDAxXSDvloBm6NmU8GXYPt3TGu7t9W2GV0Y-SspHzdf-l8PU9hwyLmRuc2NyeXB0LWNlcnQuZG5zLnRpYXIuYXBw : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "ef968066e8d994f065d83eddd31aeeedf56d8657463e4aca47cdd7fe97c3d4f6"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\3" "dns" "\4" "tiar" "\3" "app" "\0"
#endif
#ifdef UPSTREAM_P184
  //sdns://AgEAAAAAAAAACjEwMy4yLjU3LjUgmOPV5TavKVjNL38U9wTvSidtJeM81l8uZfXk8nJ8EzARcHVibGljLmRucy5paWouanAKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P185
  //sdns://AQcAAAAAAAAAEjE3Mi4xMDQuOTMuODA6MTQ0MyAyuHY-8b9lNqHeahPAzW9IoXnjiLaZpTeNbVs8TN9UUxsyLmRuc2NyeXB0LWNlcnQuanAudGlhci5hcHA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "172.104.93.8"
  #define UPSTREAM_PORT 1443
  #define UPSTREAM_PUBKEY "32b8763ef1bf6536a1de6a13c0cd6f48a179e388b699a5378d6d5b3c4cdf5453"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\2" "jp" "\4" "tiar" "\3" "app" "\0"
#endif
#ifdef UPSTREAM_P186
  //sdns://AgcAAAAAAAAADTE3Mi4xMDQuOTMuODCgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984LanAudGlhci5hcHAKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P187
  //sdns://AgcAAAAAAAAAIFsyNDAwOjg5MDI6OmYwM2M6OTFmZjpmZWRhOmM1MTRdoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOC2pwLnRpYXIuYXBwCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P188
  //sdns://AQcAAAAAAAAAJVsyNDAwOjg5MDI6OmYwM2M6OTFmZjpmZWRhOmM1MTRdOjE0NDMgMrh2PvG_ZTah3moTwM1vSKF544i2maU3jW1bPEzfVFMbMi5kbnNjcnlwdC1jZXJ0LmpwLnRpYXIuYXBw : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "32b8763ef1bf6536a1de6a13c0cd6f48a179e388b699a5378d6d5b3c4cdf5453"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\2" "jp" "\4" "tiar" "\3" "app" "\0"
#endif
#ifdef UPSTREAM_P189
  //sdns://AgcAAAAAAAAAAAANanAudGlhcmFwLm9yZwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P190
  //sdns://AgcAAAAAAAAAG1syNjA2OjQ3MDA6MzAzNjo6NjgxYjo5NmFhXQANanAudGlhcmFwLm9yZwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P191
  //sdns://AgYAAAAAAAAADjExNi4yMDIuMTc2LjI2oMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOD2RvaC5saWJyZWRucy5ncgovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P192
  //sdns://AgIAAAAAAAAADjExNi4yMDIuMTc2LjI2oMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOD2RvaC5saWJyZWRucy5ncgQvYWRz : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P193
  //sdns://AQcAAAAAAAAAEjEzNi4yNDQuOTcuMTE0OjQ0MyAon-lfTOhBf_V6PzB8JAzeGSYxEaKUiTfIQblFoPWHjCUyLmRuc2NyeXB0LWNlcnQuY2hld2JhY2NhLm1lZ2FuZXJkLm5s : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "136.244.97.11"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "289fe95f4ce8417ff57a3f307c240cde19263111a2948937c841b945a0f5878c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "chewbacca" "\10" "meganerd" "\2" "nl" "\0"
#endif
#ifdef UPSTREAM_P194
  //sdns://AgcAAAAAAAAADjEzNi4yNDQuOTcuMTE0IPzeORHpBJHobi2cNX3_9XQfsFz8cUVhWC_BDJQm1PxCFWNoZXdiYWNjYS5tZWdhbmVyZC5ubAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P195
  //sdns://AgcAAAAAAAAAKFsyMDAxOjE5ZjA6NTAwMTpjYmI6NTQwMDowM2ZmOmZlMDc6ZjcwZF0g_N45EekEkehuLZw1ff_1dB-wXPxxRWFYL8EMlCbU_EIVY2hld2JhY2NhLm1lZ2FuZXJkLm5sCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P196
  //sdns://AQcAAAAAAAAAK1syMDAxOjE5ZjA6NTAwMTpjYmI6NTQwMDozZmY6ZmUwNzpmNzBkXTo0NDMgKJ_pX0zoQX_1ej8wfCQM3hkmMRGilIk3yEG5RaD1h4wlMi5kbnNjcnlwdC1jZXJ0LmNoZXdiYWNjYS5tZWdhbmVyZC5ubA : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "289fe95f4ce8417ff57a3f307c240cde19263111a2948937c841b945a0f5878c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "chewbacca" "\10" "meganerd" "\2" "nl" "\0"
#endif
#ifdef UPSTREAM_P197
  //sdns://AgMAAAAAAAAAAAAXYWRibG9jay5kb2gubXVsbHZhZC5uZXQKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P198
  //sdns://AgcAAAAAAAAAAAAPZG9oLm11bGx2YWQubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P199
  //sdns://AgcAAAAAAAAACjQ1LjkwLjMwLjAgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkWYW55Y2FzdC5kbnMubmV4dGRucy5pbwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P200
  //sdns://AgcAAAAAAAAADVsyYTA3OmE4YzA6Ol0gmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkWYW55Y2FzdC5kbnMubmV4dGRucy5pbwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P201
  //sdns://AgcAAAAAAAAAACCaOjT3J965vKUQA9nOnDn48n3ZxSQpAcK6saROY1oCGQ5kbnMubmV4dGRucy5pbw8vZG5zY3J5cHQtcHJveHk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P202
  //sdns://AgcAAAAAAAAADDk1LjIxNS4xOS41M6DMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zgtkbnMubmphbC5sYQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P203
  //sdns://AQcAAAAAAAAADTcwLjM2LjE3MC4xMjYgHRhodSnh6n0lyl8T0d5e2OSapsrl455sspOSW_cLlQ0cMi5kbnNjcnlwdC1jZXJ0Lm9wZW5pbnRlcm5ldA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "70.36.170.126"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "1d18687529e1ea7d25ca5f13d1de5ed8e49aa6cae5e39e6cb293925bf70b950d"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\14" "openinternet" "\0"
#endif
#ifdef UPSTREAM_P204
  //sdns://AQIAAAAAAAAAETUxLjM4LjgzLjE0MTo1MzUzIMwm9_oYw26P4JIVoDhJ_5kFDdNxX1ke4fEzL1V5bwEjFzIuZG5zY3J5cHQtY2VydC5vc3p4LmNv : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "51.38.83.14"
  #define UPSTREAM_PORT 5353
  #define UPSTREAM_PUBKEY "cc26f7fa18c36e8fe09215a03849ff99050dd3715f591ee1f1332f55796f0123"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\4" "oszx" "\2" "co" "\0"
#endif
#ifdef UPSTREAM_P205
  //sdns://AQcAAAAAAAAAEzE0OS4yOC4xMDEuMTE5Ojg0NDMgVaFV4a8StIfx8fnCxDxVlxppqm-hJYyCKqtMtQENnCwkMi5kbnNjcnlwdC1jZXJ0LnBsdXRvbi5wbGFuOS1kbnMuY29t : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "149.28.101.11"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "55a155e1af12b487f1f1f9c2c43c55971a69aa6fa1258c822aab4cb5010d9c2c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\6" "pluton" "\11" "plan9-dns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P206
  //sdns://AgcAAAAAAAAADjE0OS4yOC4xMDEuMTE5IJo6NPcn3rm8pRAD2c6cOfjyfdnFJCkBwrqxpE5jWgIZFHBsdXRvbi5wbGFuOS1kbnMuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P207
  //sdns://AgcAAAAAAAAAJ1syMDAxOjE5ZjA6OTAwMjpkZTQ6NTQwMDo0ZmY6ZmUwODo3ZGUzXSCaOjT3J965vKUQA9nOnDn48n3ZxSQpAcK6saROY1oCGRRwbHV0b24ucGxhbjktZG5zLmNvbQovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P208
  //sdns://AQcAAAAAAAAAEzIxNi4yMzguODAuMjE5Ojg0NDMgKmPCui35rtOj9yk7c07sEtC_Khyo_9_HcpO23GCroNskMi5kbnNjcnlwdC1jZXJ0LmhlbGlvcy5wbGFuOS1kbnMuY29t : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "216.238.80.21"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "2a63c2ba2df9aed3a3f7293b734eec12d0bf2a1ca8ffdfc77293b6dc60aba0db"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\6" "helios" "\11" "plan9-dns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P209
  //sdns://AgcAAAAAAAAADjIxNi4yMzguODAuMjE5IJo6NPcn3rm8pRAD2c6cOfjyfdnFJCkBwrqxpE5jWgIZFGhlbGlvcy5wbGFuOS1kbnMuY29tCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P210
  //sdns://AgcAAAAAAAAAKFsyMDAxOjE5ZjA6YjQwMDoxZDhjOjU0MDA6NGZmOmZlMTE6YjE1YV0gmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkUaGVsaW9zLnBsYW45LWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P211
  //sdns://AQcAAAAAAAAAEjIwNy4yNDYuODcuOTY6ODQ0MyCwmQlIDpKk8SiiyrJbPgKhHxCrBJLb8ZWlu6tvr1KvkyQyLmRuc2NyeXB0LWNlcnQua3Jvbm9zLnBsYW45LWRucy5jb20 : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "207.246.87.9"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "b09909480e92a4f128a2cab25b3e02a11f10ab0492dbf195a5bbab6faf52af93"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\6" "kronos" "\11" "plan9-dns" "\3" "com" "\0"
#endif
#ifdef UPSTREAM_P212
  //sdns://AgcAAAAAAAAADTIwNy4yNDYuODcuOTYgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkUa3Jvbm9zLnBsYW45LWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P213
  //sdns://AgcAAAAAAAAAJVsyMDAxOjE5ZjA6NTozYmQ3OjU0MDA6NGZmOmZlMDU6ZGE4M10gmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkUa3Jvbm9zLnBsYW45LWRucy5jb20KL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P214
  //sdns://AQcAAAAAAAAAEzE2NC42OC4xMjEuMTYyOjQ0NDMgHtKNfXpUMzPyLnXK8DauHpWm1Rqhz7LqwBBmSzdY9BIcMi5kbnNjcnlwdC1jZXJ0LnByeXY4Ym9pLm9yZw : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "164.68.121.16"
  #define UPSTREAM_PORT 4443
  #define UPSTREAM_PUBKEY "1ed28d7d7a543333f22e75caf036ae1e95a6d51aa1cfb2eac010664b3758f412"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "pryv8boi" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P215
  //sdns://AgcAAAAAAAAADDQ1Ljc2LjExMy4zMaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhBkb2guc2VieS5pbzo4NDQzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P216
  //sdns://AgcAAAAAAAAADTEzOS45OS4yMjIuNzKgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984NZG9oLTIuc2VieS5pbwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P217
  //sdns://AgcAAAAAAAAAACC2vD25TAYM7EnyCH8Xw1-0g5OccnTsGH9vQUUH0njRtAxkbnMudHduaWMudHcKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P218
  //sdns://AQMAAAAAAAAADTkuOS45LjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "9.9.9.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P219
  //sdns://AQMAAAAAAAAAEzE0OS4xMTIuMTEyLjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "149.112.112.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P220
  //sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0 : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "9.9.9."
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P221
  //sdns://AQMAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0 : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "149.112.112."
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P222
  //sdns://AQMAAAAAAAAAFDE0OS4xMTIuMTEyLjExMjo4NDQzIGfIR7jIdYzRICRVQ751Z0bfNN8dhMALjEcDaN-CHYY-GTIuZG5zY3J5cHQtY2VydC5xdWFkOS5uZXQ : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "149.112.112.11"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P223
  //sdns://AQYAAAAAAAAADTkuOS45LjEyOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "9.9.9.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P224
  //sdns://AQYAAAAAAAAAEzE0OS4xMTIuMTEyLjEyOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "149.112.112.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P225
  //sdns://AQYAAAAAAAAAEzE0OS4xMTIuMTEyLjEwOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA : 
  // ! NO DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "149.112.112.1"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\5" "quad9" "\3" "net" "\0"
#endif
#ifdef UPSTREAM_P226
  //sdns://AgMAAAAAAAAACDkuOS45LjExICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczExLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P227
  //sdns://AgMAAAAAAAAADjE0OS4xMTIuMTEyLjExICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczExLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P228
  //sdns://AgMAAAAAAAAABzkuOS45LjkgKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoSZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P229
  //sdns://AgMAAAAAAAAADTE0OS4xMTIuMTEyLjkgKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoSZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P230
  //sdns://AgMAAAAAAAAADzE0OS4xMTIuMTEyLjExMiAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihFkbnMucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P231
  //sdns://AgYAAAAAAAAACDkuOS45LjEyICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczEyLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P232
  //sdns://AgYAAAAAAAAADjE0OS4xMTIuMTEyLjEyICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczEyLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P233
  //sdns://AgYAAAAAAAAACDkuOS45LjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczEwLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P234
  //sdns://AgYAAAAAAAAADjE0OS4xMTIuMTEyLjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKE2RuczEwLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P235
  //sdns://AgMAAAAAAAAACDkuOS45LjExICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczExLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P236
  //sdns://AgMAAAAAAAAADjE0OS4xMTIuMTEyLjExICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczExLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P237
  //sdns://AgMAAAAAAAAABzkuOS45LjkgKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zOS5xdWFkOS5uZXQ6NTA1MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P238
  //sdns://AgMAAAAAAAAADTE0OS4xMTIuMTEyLjkgKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zOS5xdWFkOS5uZXQ6NTA1MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P239
  //sdns://AgMAAAAAAAAADzE0OS4xMTIuMTEyLjExMiAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihJkbnMucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P240
  //sdns://AgYAAAAAAAAACDkuOS45LjEyICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEyLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P241
  //sdns://AgYAAAAAAAAADjE0OS4xMTIuMTEyLjEyICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEyLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P242
  //sdns://AgYAAAAAAAAACDkuOS45LjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEwLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P243
  //sdns://AgYAAAAAAAAADjE0OS4xMTIuMTEyLjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEwLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P244
  //sdns://AgMAAAAAAAAADVsyNjIwOmZlOjoxMV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTEucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P245
  //sdns://AgMAAAAAAAAAEFsyNjIwOmZlOjpmZToxMV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTEucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P246
  //sdns://AgMAAAAAAAAADVsyNjIwOmZlOjpmZV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoRZG5zLnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P247
  //sdns://AgMAAAAAAAAADFsyNjIwOmZlOjo5XSAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihFkbnMucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P248
  //sdns://AgMAAAAAAAAAD1syNjIwOmZlOjpmZTo5XSAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihJkbnM5LnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P249
  //sdns://AgYAAAAAAAAADVsyNjIwOmZlOjoxMl0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTIucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P250
  //sdns://AgYAAAAAAAAAEFsyNjIwOmZlOjpmZToxMl0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTIucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P251
  //sdns://AgYAAAAAAAAADVsyNjIwOmZlOjoxMF0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTAucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P252
  //sdns://AgYAAAAAAAAAEFsyNjIwOmZlOjpmZToxMF0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoTZG5zMTAucXVhZDkubmV0OjQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P253
  //sdns://AgMAAAAAAAAADVsyNjIwOmZlOjoxMV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTEucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P254
  //sdns://AgMAAAAAAAAAEFsyNjIwOmZlOjpmZToxMV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTEucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P255
  //sdns://AgMAAAAAAAAADVsyNjIwOmZlOjpmZV0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoSZG5zLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P256
  //sdns://AgMAAAAAAAAADFsyNjIwOmZlOjo5XSAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihJkbnMucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P257
  //sdns://AgMAAAAAAAAAD1syNjIwOmZlOjpmZTo5XSAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElihNkbnM5LnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P258
  //sdns://AgYAAAAAAAAADVsyNjIwOmZlOjoxMl0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTIucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P259
  //sdns://AgYAAAAAAAAAEFsyNjIwOmZlOjpmZToxMl0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTIucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P260
  //sdns://AgYAAAAAAAAADVsyNjIwOmZlOjoxMF0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTAucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P261
  //sdns://AgYAAAAAAAAAEFsyNjIwOmZlOjpmZToxMF0gKhX11qy258CQGt5Ou8dDsszUiQMrRuFkLwaTaDABJYoUZG5zMTAucXVhZDkubmV0OjUwNTMKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P262
  //sdns://AQIAAAAAAAAADzEwNC4xNTUuMjM3LjIyNSAnIH_VEgToNntINABd-f_R0wu-KpwzY55u2_iu2R1A2CAyLmRuc2NyeXB0LWNlcnQuc2FmZXN1cmZlci5jby5ueg : 
  // ! NO DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "104.155.237.225"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "27207fd51204e8367b4834005df9ffd1d30bbe2a9c33639e6edbf8aed91d40d8"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\12" "safesurfer" "\2" "co" "\2" "nz" "\0"
#endif
#ifdef UPSTREAM_P263
  //sdns://AgAAAAAAAAAAACBqUGKw0XjVVvFjsTsbDxlDXQJYgpHMdVid_ubrEcjVwxFkb2guc2FmZXN1cmZlci5pbwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P264
  //sdns://AQcAAAAAAAAAFDExOC4yNy4xMDguMTQwOjUwNDQzIPL_JdttytAhcocG8vZH5EVk-uQKKose72bD0ji5G-xlIjIuZG5zY3J5cHQtY2VydC5zYWxkbnMwMS50eXBlcS5vcmc : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "118.27.108.14"
  #define UPSTREAM_PORT 50443
  #define UPSTREAM_PUBKEY "f2ff25db6dcad021728706f2f647e44564fae40a2a8b1eef66c3d238b91bec65"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "saldns01" "\5" "typeq" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P265
  //sdns://AQcAAAAAAAAAFTEzMy4xMzAuMTE4LjEwMzo1MDQ0MyB7SI0q4_Ff8lFRUCbjPtcAQ3HfdWlLxyGDUUNc3NUZdiIyLmRuc2NyeXB0LWNlcnQuc2FsZG5zMDIudHlwZXEub3Jn : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "133.130.118.10"
  #define UPSTREAM_PORT 50443
  #define UPSTREAM_PUBKEY "7b488d2ae3f15ff251515026e33ed7004371df75694bc7218351435cdcd51976"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "saldns02" "\5" "typeq" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P266
  //sdns://AQcAAAAAAAAAFDEzMy4xMzAuOTguMjUwOjUwNDQzIFl1NfOwMd24kRlr0mXR4rKo-c_jMV7DBUVooDEY1xFeIjIuZG5zY3J5cHQtY2VydC5zYWxkbnMwMy50eXBlcS5vcmc : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "133.130.98.25"
  #define UPSTREAM_PORT 50443
  #define UPSTREAM_PUBKEY "597535f3b031ddb891196bd265d1e2b2a8f9cfe3315ec3054568a03118d7115e"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\10" "saldns03" "\5" "typeq" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P267
  //sdns://AgcAAAAAAAAADjE5OS4xODAuMTMwLjM5oDUJq9J2eoL0zQJHsLcq9AQ3obsl8h1hFreCavqWy4TdIGpQYrDReNVW8WOxOxsPGUNdAliCkcx1WJ3-5usRyNXDFHNieS1kb2gubGltb3RlbHUub3JnCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P268
  //sdns://AQcAAAAAAAAAEzE5OS4xODAuMTMwLjM5Ojg0NDMg1U5MYSDK58uVdJ8dKtp0UZaCKSG0znwQLVHYKk1QyuwcMi5kbnNjcnlwdC1jZXJ0LnNieS1saW1vdGVsdQ : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "199.180.130.3"
  #define UPSTREAM_PORT 8443
  #define UPSTREAM_PUBKEY "d54e4c6120cae7cb95749f1d2ada745196822921b4ce7c102d51d82a4d50caec"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\14" "sby-limotelu" "\0"
#endif
#ifdef UPSTREAM_P269
  //sdns://AQcAAAAAAAAADTUxLjE1LjEyMi4yNTAg6Q3ZfapcbHgiHKLF7QFoli0Ty1Vsz3RXs1RUbxUrwZAcMi5kbnNjcnlwdC1jZXJ0LnNjYWxld2F5LWFtcw : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "51.15.122.250"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "e90dd97daa5c6c78221ca2c5ed0168962d13cb556ccf7457b354546f152bc190"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\14" "scaleway-ams" "\0"
#endif
#ifdef UPSTREAM_P270
  //sdns://AQcAAAAAAAAAFlsyMDAxOmJjODoxODIwOjUwZDo6MV0g6Q3ZfapcbHgiHKLF7QFoli0Ty1Vsz3RXs1RUbxUrwZAcMi5kbnNjcnlwdC1jZXJ0LnNjYWxld2F5LWFtcw : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "e90dd97daa5c6c78221ca2c5ed0168962d13cb556ccf7457b354546f152bc190"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\14" "scaleway-ams" "\0"
#endif
#ifdef UPSTREAM_P271
  //sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "212.47.228.136"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "e801b84ea606bfb0bac0ce43445bb15eba64b02fa3c4aa31ae10636a0790324d"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\2" "fr" "\10" "dnscrypt" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P272
  //sdns://AQcAAAAAAAAAF1syMDAxOmJjODo0N2IwOjFhMDE6OjFdIOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "e801b84ea606bfb0bac0ce43445bb15eba64b02fa3c4aa31ae10636a0790324d"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\2" "fr" "\10" "dnscrypt" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P273
  //sdns://AQcAAAAAAAAAEzE4NS42Ni4xNDMuMTc4OjUzNTMg-Y2MQmGOXiggAEKulN-ITGEn_Kj3TIP1UK1X2wh3o7wXMi5kbnNjcnlwdC1jZXJ0LnNlcmJpY2E : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "185.66.143.17"
  #define UPSTREAM_PORT 5353
  #define UPSTREAM_PUBKEY "f98d8c42618e5e28200042ae94df884c6127fca8f74c83f550ad57db0877a3bc"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "serbica" "\0"
#endif
#ifdef UPSTREAM_P274
  //sdns://AQMAAAAAAAAADzE2My4xNzIuMTgwLjEyNSDfYnO_x1IZKotaObwMhaw_-WRF1zZE9mJygl01WPGh_x8yLmRuc2NyeXB0LWNlcnQuc2Z3LnNjYWxld2F5LWZy : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "163.172.180.125"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "df6273bfc752192a8b5a39bc0c85ac3ff96445d73644f66272825d3558f1a1ff"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\3" "sfw" "\13" "scaleway-fr" "\0"
#endif
#ifdef UPSTREAM_P275
  //sdns://AQcAAAAAAAAACzUyLjc3LjMuMjE1IDb9YzoMbw-DD4Ql0GG-maGsuKFCEor_AW69i7NlvWuXIDIuZG5zY3J5cHQtY2VydC5zdGFycnlkbnMucGxhbmV0 : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "52.77.3.215"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "36fd633a0c6f0f830f8425d061be99a1acb8a142128aff016ebd8bb365bd6b97"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "starrydns" "\6" "planet" "\0"
#endif
#ifdef UPSTREAM_P276
  //sdns://AQcAAAAAAAAAKFsyNDA2OmRhMTg6Njc2OjQxMDI6ODdiOTplMjk5OjJhNWE6ODk0Yl0gNv1jOgxvD4MPhCXQYb6Zoay4oUISiv8Bbr2Ls2W9a5cgMi5kbnNjcnlwdC1jZXJ0LnN0YXJyeWRucy5wbGFuZXQ : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "36fd633a0c6f0f830f8425d061be99a1acb8a142128aff016ebd8bb365bd6b97"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\11" "starrydns" "\6" "planet" "\0"
#endif
#ifdef UPSTREAM_P277
  //sdns://AgMAAAAAAAAADTQ1LjE1My4xODcuOTYAGGRuc3NlLW5vYWRzLmFsZWtiZXJnLm5ldAovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P278
  //sdns://AQcAAAAAAAAAEjQ1LjE1My4xODcuOTY6NDM0MyDxcH8AVvN5Rqr3-HUqRjpgUFVw3NgiJ-IGTCbEVu__7x8yLmRuc2NyeXB0LWNlcnQuc3RoLWRuc2NyeXB0LW5s : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "45.153.187.9"
  #define UPSTREAM_PORT 4343
  #define UPSTREAM_PUBKEY "f1707f0056f37946aaf7f8752a463a60505570dcd82227e2064c26c456efffef"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\17" "sth-dnscrypt-nl" "\0"
#endif
#ifdef UPSTREAM_P279
  //sdns://AQcAAAAAAAAAGlsyYTA5OmNkNDI6Zjo0MjViOjoxXTo0MzQzIPFwfwBW83lGqvf4dSpGOmBQVXDc2CIn4gZMJsRW7__vHzIuZG5zY3J5cHQtY2VydC5zdGgtZG5zY3J5cHQtbmw : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "f1707f0056f37946aaf7f8752a463a60505570dcd82227e2064c26c456efffef"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\17" "sth-dnscrypt-nl" "\0"
#endif
#ifdef UPSTREAM_P280
  //sdns://AgcAAAAAAAAADTQ1LjE1My4xODcuOTagzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZG5zc2UuYWxla2JlcmcubmV0Ci9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P281
  //sdns://AgMAAAAAAAAAACAqFfXWrLbnwJAa3k67x0OyzNSJAytG4WQvBpNoMAElig1kbnMuc3dpdGNoLmNoCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P282
  //sdns://AQcAAAAAAAAAEDg5LjU4LjYuMTY5OjQ0MzQgB4isFl7gD2-efHhMEtFjyCz_nHFCaQ8OsbBTgZCa3zsgMi5kbnNjcnlwdC1jZXJ0LnRlY2hzYXZpb3Vycy5vcmc : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "89.58.6.16"
  #define UPSTREAM_PORT 4434
  #define UPSTREAM_PUBKEY "0788ac165ee00f6f9e7c784c12d163c82cff9c7142690f0eb1b05381909adf3b"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\14" "techsaviours" "\3" "org" "\0"
#endif
#ifdef UPSTREAM_P283
  //sdns://AgEAAAAAAAAACTEwMS42LjYuNiBZPi1Jp0AjVVUmrvm3QisZ5bixZzkbbe5e0pKxyiOnTA4xMDEuNi42LjY6ODQ0MwovZG5zLXF1ZXJ5 : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P284
  //sdns://AgcAAAAAAAAADDg5LjIzMy40My43MaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhl1bmljYXN0LnVuY2Vuc29yZWRkbnMub3JnCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P285
  //sdns://AgcAAAAAAAAAElsyYTAxOjNhMDo1Mzo1Mzo6XaDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5iBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zhl1bmljYXN0LnVuY2Vuc29yZWRkbnMub3JnCi9kbnMtcXVlcnk : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P286
  //sdns://AgcAAAAAAAAADjkxLjIzOS4xMDAuMTAwoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOGWFueWNhc3QudW5jZW5zb3JlZGRucy5vcmcKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P287
  //sdns://AgcAAAAAAAAAEVsyMDAxOjY3YzoyOGE0OjpdoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOGWFueWNhc3QudW5jZW5zb3JlZGRucy5vcmcKL2Rucy1xdWVyeQ : 
  //non-DNSCrypt
#endif
#ifdef UPSTREAM_P288
  //sdns://AQMAAAAAAAAAEDEwMy4xNi4xMzEuNzc6NTQgnRNtOLv4IzxEfkbLFOaHa-ncLImdQiP-pS1jaFY5jlUdMi5kbnNjcnlwdC1jZXJ0LnVzZXJzcGFjZS1ibmU : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "103.16.131.7"
  #define UPSTREAM_PORT 54
  #define UPSTREAM_PUBKEY "9d136d38bbf8233c447e46cb14e6876be9dc2c899d4223fea52d636856398e55"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\15" "userspace-bne" "\0"
#endif
#ifdef UPSTREAM_P289
  //sdns://AQMAAAAAAAAAEjEwMy4yMzYuMTYyLjExOTo1NCBPr5jCD_2geOTMmS5LgQg_v79pgppTm3vLZhe_oahbgR0yLmRuc2NyeXB0LWNlcnQudXNlcnNwYWNlLW1lbA : 
  // DNSSec
  // No-log
  // ! FILTERING
  #define UPSTREAM_HOST "103.236.162.11"
  #define UPSTREAM_PORT 54
  #define UPSTREAM_PUBKEY "4faf98c20ffda078e4cc992e4b81083fbfbf69829a539b7bcb6617bfa1a85b81"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\15" "userspace-mel" "\0"
#endif
#ifdef UPSTREAM_P290
  //sdns://AQMAAAAAAAAAJVsyNDA0Ojk0MDA6MTowOjIxNjozZWZmOmZlZjA6MTgwYV06NTQgnRNtOLv4IzxEfkbLFOaHa-ncLImdQiP-pS1jaFY5jlUdMi5kbnNjcnlwdC1jZXJ0LnVzZXJzcGFjZS1ibmU : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "9d136d38bbf8233c447e46cb14e6876be9dc2c899d4223fea52d636856398e55"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\15" "userspace-bne" "\0"
#endif
#ifdef UPSTREAM_P291
  //sdns://AQMAAAAAAAAAJVsyNDA0Ojk0MDA6MzowOjIxNjozZWZmOmZlZTA6N2Y2OV06NTQgT6-Ywg_9oHjkzJkuS4EIP7-_aYKaU5t7y2YXv6GoW4EdMi5kbnNjcnlwdC1jZXJ0LnVzZXJzcGFjZS1tZWw : 
  // DNSSec
  // No-log
  // ! FILTERING
  //[ipv6]
  #define UPSTREAM_PUBKEY "4faf98c20ffda078e4cc992e4b81083fbfbf69829a539b7bcb6617bfa1a85b81"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\15" "userspace-mel" "\0"
#endif
#ifdef UPSTREAM_P292
  //sdns://AQcAAAAAAAAADzEwNC4yMzguMTg2LjE5MiDtST2M6teQZk8GPEe3lZojaS18kDY8nkPMtZF75bQe5R0yLmRuc2NyeXB0LWNlcnQudi5kbnNjcnlwdC51aw : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "104.238.186.192"
  #define UPSTREAM_PORT 443
  #define UPSTREAM_PUBKEY "ed493d8cead790664f063c47b7959a23692d7c90363c9e43ccb5917be5b41ee5"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\1" "v" "\10" "dnscrypt" "\2" "uk" "\0"
#endif
#ifdef UPSTREAM_P293
  //sdns://AQcAAAAAAAAAKFsyMDAxOjE5ZjA6NzQwMjoxNTc0OjU0MDA6MmZmOmZlNjY6MmNmZl0g7Uk9jOrXkGZPBjxHt5WaI2ktfJA2PJ5DzLWRe-W0HuUdMi5kbnNjcnlwdC1jZXJ0LnYuZG5zY3J5cHQudWs : 
  // DNSSec
  // No-log
  // No-filtering
  //[ipv6]
  #define UPSTREAM_PUBKEY "ed493d8cead790664f063c47b7959a23692d7c90363c9e43ccb5917be5b41ee5"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\1" "v" "\10" "dnscrypt" "\2" "uk" "\0"
#endif
#ifdef UPSTREAM_P294
  //sdns://AQcAAAAAAAAAEzE0My4yNDQuMzMuNzQ6MTUzNTMgFTXwu5MfYkBOrRpDeoB-yOWEjCnf-l3yixhtuzuPBskfMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZS5kbnMudGVzdA : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "143.244.33.7"
  #define UPSTREAM_PORT 15353
  #define UPSTREAM_PUBKEY "1535f0bb931f62404ead1a437a807ec8e5848c29dffa5df28b186dbb3b8f06c9"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\6" "secure" "\3" "dns" "\4" "test" "\0"
#endif
#ifdef UPSTREAM_P295
  //sdns://AQcAAAAAAAAAFDIzLjIyNi4xMzQuMjQyOjE1MzUzII_Le5DiGa3AfdRxR7DRt52ZaexL_22aLfjDJwp5saIsHzIuZG5zY3J5cHQtY2VydC5zZWN1cmUuZG5zLnRlc3Q : 
  // DNSSec
  // No-log
  // No-filtering
  #define UPSTREAM_HOST "23.226.134.24"
  #define UPSTREAM_PORT 15353
  #define UPSTREAM_PUBKEY "8fcb7b90e219adc07dd47147b0d1b79d9969ec4bff6d9a2df8c3270a79b1a22c"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\6" "secure" "\3" "dns" "\4" "test" "\0"
#endif
#ifdef UPSTREAM_P296
  //sdns://AQQAAAAAAAAAEDc3Ljg4LjguNzg6MTUzNTMg04TAccn3RmKvKszVe13MlxTUB7atNgHhrtwG1W1JYyciMi5kbnNjcnlwdC1jZXJ0LmJyb3dzZXIueWFuZGV4Lm5ldA : 
  // ! NO DNSSec
  // ! LOGGING
  // No-filtering
  #define UPSTREAM_HOST "77.88.8.7"
  #define UPSTREAM_PORT 15353
  #define UPSTREAM_PUBKEY "d384c071c9f74662af2accd57b5dcc9714d407b6ad3601e1aedc06d56d496327"
  #define UPSTREAM_SRVNAME "\1" "2" "\15" "dnscrypt-cert" "\7" "browser" "\6" "yandex" "\3" "net" "\0"
#endif
